version: "3.9"
services:
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    volumes:
    - 'db_volume:/var/lib/postgresql/data'
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}     
    networks:
      - alura_net

  web:
    container_name: app_alura
    image: app:5.0
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}      
    networks:
      - alura_net
    depends_on:
      - db

volumes:
  db_volume:
networks:
  alura_net:
    driver: bridge